### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by lucascardo12** [keinou/gauge_animated#1]
It would be good to place a point dynamically at the end of the percentage indicator. 
stay tip

**Comment by keinou** [comment]
It will be implemented in 0.8.1

**Comment by esiscd2000** [comment]
In case I place the gauge in build(BuildContext context) function, there is no initial value of the gauge or Driver. It is also not taking the added value of the driver after initialized. I suggest to add initialValue as option. Later on when I want to change value, I change the Driver value. This will support when I leave the route and pop() back. Without initialValue, the new build will always shows zero gauge.
